spring:
  application:
    name: zipcheck
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/zipcheck?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: contest76-bucket