# -----------------------------------------------
# ???????? ?????? ?? (2023.02.21~)
# -----------------------------------------------

# 1?: ?????
policy.repayment-rules.SEOUL.description=?????
policy.repayment-rules.SEOUL.deposit-limit=16500
policy.repayment-rules.SEOUL.repayment-amount=5500

# 2?: ?????? ? (?? ??)
policy.repayment-rules.OVERCROWDED.description=??????(?? ??), ???????, ???, ???, ???
policy.repayment-rules.OVERCROWDED.deposit-limit=14500
policy.repayment-rules.OVERCROWDED.repayment-amount=4800

# 3?: ??? ? (?? ??, ??? ?? ??)
# '???'? 3?, '??'? 2???? ??? ??? ???? 3?? ??.
# '??? ??'? 3?? ??.
policy.repayment-rules.METROPOLITAN.description=???(??/??? ??), ???, ??? ???, ???, ???, ???
policy.repayment-rules.METROPOLITAN.deposit-limit=8500
policy.repayment-rules.METROPOLITAN.repayment-amount=2800

# 4?: ? ?? ??
policy.repayment-rules.OTHER.description=? ?? ??
policy.repayment-rules.OTHER.deposit-limit=7500
policy.repayment-rules.OTHER.repayment-amount=2500