apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipcheck-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipcheck
  template:
    metadata:
      labels:
        app: zipcheck
    spec:
      containers:
        - name: zipcheck-app
          image: contest76-reg.kr.ncr.ntruss.com/zipcheck-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: JWT_SECRET
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: GOOGLE_API_KEY
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: NAVER_CLIENT_ID
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: NAVER_CLIENT_SECRET
            - name: NCP_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: NCP_ACCESS_KEY
            - name: NCP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: NCP_SECRET_KEY
            - name: SOLAPI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: SOLAPI_API_KEY
            - name: SOLAPI_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: SOLAPI_API_SECRET
            # DB 비밀번호도 Secret에서 참조
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: DATASOURCE_PASSWOR
            - name: DATA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: zipcheck-secrets
                  key: DATA_API_SECRET


---
apiVersion: v1
kind: Service
metadata:
  name: zipcheck-service
spec:
  selector:
    app: zipcheck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer